sudo: required
language: node_js
node_js:
- 8.9.0
before_deploy:
- yarn build
deploy:
  provider: npm
  skip_cleanup: true
  email: harunurhan17@gmail.com
  on:
    tags: true
    repo: harunurhan/react-latex-next
    branch: master
  api_key:
    secure: sqh6iSjSv/IOT0+j8jIqLov3eUrBplyWInEnNGbdKu+wK8GvEqplJ6SOqJQNP+ENmNC9bdfof+cZsuGHp+Ts5zkvbm3ZGbVIFpshouJOP6Y3w3kBvSeGmVmem+aoa5b7avpcb8ho7SCLSeh4/5Gh1sfnkL6UOcGr6cJhRX//xjumUsEmlag7U5UfO9grPWxznTFFtp4fKPHMm+OBw92QjcDuoh2vt7/Uk4lndgYWETEqBlEJeE2lVXAZxtOp/8W4Q9Bq/3e8d+GKZPNsSwaXYv3dMlPK+MMAYfu08jWkAv76iAkAuYNTDyrgWNzjjWmdnSaISQAaZ4boIsuOg1tnumeKrIKtsrNFAeYjsgpgVlMg7bWN31yyc8eyX+FyCb75da9a3rf9f6HkVn4aTqMYfpgBPZ8CkCgqXtU7OeSQA2s/FuRDngWo5DCF2BP6fmh6hx40YhkUApLLFLWyOuoRcX1z/aikujaJJpvFAx3tKshYAiP3SvC5dwsCZo/VCVMHO8jT3Y/cndXw8wXpL97zS6hoycWgPE5HYH5lHoNdUCXPSSL8skk30TpFtlZ0Wb/3y12ziQLfoVFf/jDWdUPAjLdRnVFAne9tmfq9dfE1txX8Nl3KJm/ZkrOiJVIP4MOAp/PQaYE4GX9BHRQSWyi29N1+gBTgUKuQOGSfWNgw4EY=
